package findTheDifference
/** Find the Difference
 * You are given two strings s and t.
 *
 * String t is generated by random shuffling string s and then add one more letter
 * at a random position.
 *
 * Return the letter that was added to t.
 */
class FindTheDifference {
    fun findTheDifference(s: String, t: String): Char {
        val input = mutableMapOf<Char, Int>()
        for (letter in s) {
            input[letter] = input.getOrDefault(letter, 0) + 1
        }
        for (char in t) {
            if (!input.containsKey(char)) {
                return char
            } else {
                if (input[char] == 0) {
                    return char
                } else {
                    input[char] = input[char]!! - 1
                }
            }
        }
        return '-'
    }
}